import Header from "./components/Header";

export const metadata = {
  title: 'Page Funcionário',
  description: 'Generated by create next app',
};

export default function LayoutFuncionario({ children }) {
  return (
    <html lang='pt-br'>
      <body>
        <Header/>
        {children}
        </body>
    </html>
  );
}


