import style from './globals.css';

export const metadata = {
  title: 'Page Login',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='pt-br'>
      <body data-theme='emerald'>{children}</body>
    </html>
  );
}
